apiVersion: batch/v1
kind: Job
metadata:
  name: tlms-activity
  labels:
    tenant: CreateTenant
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: tlms-activity
        image: repo-dev.successfactors.sap.corp/plumber/tls_activity:latest
        imagePullPolicy: Always
        env:
        - name: PLATFORM_TLS_SERVERTYPE
          value: job
        - name: PLATFORM_TLS_TENANTID
          value: BizxTest 
      restartPolicy: Never